# Enable C++ support
language: cpp

# Compiler selection
compiler:
	- gcc

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
    	dist: xenial

branchs:
	only:
		- master

notifications:
  email:
    recipients:
      - tingkai@csie.io
      - qaz8899921@gmail.com
    on_success: never
    on_failure: always

before_install:
  - sudo apt-get install libboost-all-dev
	- sudo apt-get install libmysqlcppconn-dev
	- sudo apt-get install libgtkmm-3.0-dev

script: 
	- make
	- ./volleyball test
